=== ministryofjustice/opg-scanning/xsd/EPA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 (x64) (http://www.altova.com) by Elaine Matthews (Banctec Limited) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="EPA">
		<xs:annotation>
			<xs:documentation>EPA</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Page">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BURN"/>
							<xs:element ref="PhysicalPage"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Salutation"/>
				<xs:element ref="LastName"/>
				<xs:element ref="Forename"/>
				<xs:element ref="OtherForenames"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Salutation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Mr" type="xs:boolean"/>
				<xs:element name="Mrs" type="xs:boolean"/>
				<xs:element name="Ms" type="xs:boolean"/>
				<xs:element name="Miss" type="xs:boolean"/>
				<xs:element name="Other" type="xs:boolean"/>
				<xs:element name="OtherName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Address1" type="xs:string"/>
				<xs:element name="Address2" type="xs:string"/>
				<xs:element name="Address3" type="xs:string"/>
				<xs:element name="TownCity" type="xs:string"/>
				<xs:element name="County" type="xs:string"/>
				<xs:element name="Postcode" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Telephone" type="xs:string"/>
	<xs:element name="DOB" type="xs:string"/>
	<xs:element name="Email" type="xs:string"/>
	<xs:element name="Attorney">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="CompanyName"/>
				<xs:element ref="Address"/>
				<xs:element ref="DXDetails"/>
				<xs:element ref="DOB"/>
				<xs:element ref="Telephone"/>
				<xs:element ref="Email"/>
				<xs:element ref="Occupation"/>
				<xs:element ref="Relationship"/>
				<xs:element name="Appointment">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Jointly" type="xs:boolean"/>
							<xs:element name="JointlyAndSeverally" type="xs:boolean"/>
							<xs:element name="Alone" type="xs:boolean"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DXDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DXNumber" type="xs:string"/>
				<xs:element name="DXExchange" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CivilPartnerSpouse" type="xs:boolean"/>
				<xs:element name="Child" type="xs:boolean"/>
				<xs:element name="OtherRelation" type="xs:boolean"/>
				<xs:element name="NoRelation" type="xs:boolean"/>
				<xs:element name="Solicitor" type="xs:boolean"/>
				<xs:element name="OtherProfessional" type="xs:boolean"/>
				<xs:element name="OtherName" type="xs:string">
					<xs:annotation>
						<xs:documentation>If other or other professional, please specify</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Notification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NoticeDate" type="xs:string"/>
				<xs:element name="LastName" type="xs:string"/>
				<xs:element name="FirstName" type="xs:string"/>
				<xs:element ref="Address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IorWe">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="I" type="xs:boolean"/>
				<xs:element name="We" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Date" type="xs:string"/>
	<xs:element name="YesorNo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Yes" type="xs:boolean"/>
				<xs:element name="No" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LastName" type="xs:string"/>
	<xs:element name="Forename" type="xs:string"/>
	<xs:element name="Declaration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Signed" type="xs:boolean"/>
				<xs:element ref="Date"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompanyName" type="xs:string"/>
	<xs:element name="Occupation" type="xs:string"/>
	<xs:element name="OtherForenames" type="xs:string"/>
	<xs:element name="Relative">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="FullName" type="xs:string"/>
				<xs:element name="Relationship" type="xs:string"/>
				<xs:element name="Address1" type="xs:string"/>
				<xs:element name="Address2" type="xs:string"/>
				<xs:element name="Address3" type="xs:string"/>
				<xs:element ref="Date"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BURN" type="xs:string"/>
	<xs:element name="PhysicalPage" type="xs:int"/>
</xs:schema>

=== ministryofjustice/opg-scanning/testdata/xml/EPA-valid.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<EPA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EPA.xsd">
    <Page>
        <BURN />
        <PhysicalPage>1</PhysicalPage>
    </Page>
    <Page>
        <BURN />
        <PhysicalPage>2</PhysicalPage>
    </Page>
    <Page>
        <BURN />
        <PhysicalPage>3</PhysicalPage>
    </Page>
    <Page>
        <BURN />
        <PhysicalPage>4</PhysicalPage>
    </Page>
</EPA>
