=== ministryofjustice/opg-scanning/xsd/LP2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 (x64) (http://www.altova.com) by Elaine Matthews (Banctec Limited) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
    <xs:element name="LP2">
        <xs:annotation>
            <xs:documentation>Application to register a lasting Power of Attorney for health and welfare</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Page1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section1">
                                <xs:annotation>
                                    <xs:documentation>About the lastiing power of attorney</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Title" type="xs:string"/>
                                        <xs:element ref="FirstName"/>
                                        <xs:element ref="LastName"/>
                                        <xs:element name="PropertyFinancialAffairs" type="xs:boolean"/>
                                        <xs:element name="HealthWelfare" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section2">
                                <xs:annotation>
                                    <xs:documentation>The applicant</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DonorRegisteration" type="xs:boolean"/>
                                        <xs:element name="AttorneyRegisteration" type="xs:boolean"/>
                                        <xs:element name="Attorney" minOccurs="4" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Title" type="xs:string"/>
                                                    <xs:element ref="FirstName"/>
                                                    <xs:element ref="LastName"/>
                                                    <xs:element ref="DOB"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section3">
                                <xs:annotation>
                                    <xs:documentation>Who do you want to recieve the LPA?</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TheDonor" type="xs:boolean"/>
                                        <xs:element name="AnAttorney" type="xs:boolean"/>
                                        <xs:element name="Other" type="xs:boolean"/>
                                        <xs:element name="Title" type="xs:string"/>
                                        <xs:element ref="FirstName"/>
                                        <xs:element ref="LastName"/>
                                        <xs:element name="Company" type="xs:string"/>
                                        <xs:element ref="Address"/>
                                        <xs:element name="Post" type="xs:boolean"/>
                                        <xs:element name="Phone" type="xs:boolean"/>
                                        <xs:element name="PhoneNumber" type="xs:string"/>
                                        <xs:element name="Email" type="xs:boolean"/>
                                        <xs:element name="EmailAddress" type="xs:string"/>
                                        <xs:element name="Welsh" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page4">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section4">
                                <xs:annotation>
                                    <xs:documentation>Application Fee</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Cheque" type="xs:boolean"/>
                                        <xs:element name="Card" type="xs:boolean"/>
                                        <xs:element name="PhoneNumber" type="xs:string"/>
                                        <xs:element name="ReducedFee" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section5">
                                <xs:annotation>
                                    <xs:documentation>Signature</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Attorney" minOccurs="4" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="Date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page6" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Section6">
                                <xs:annotation>
                                    <xs:documentation>Additional Information</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Addresses" minOccurs="4" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Title" type="xs:string"/>
                                                    <xs:element ref="FirstName"/>
                                                    <xs:element ref="LastName"/>
                                                    <xs:element ref="Address"/>
                                                    <xs:element name="EmailAddress" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="InfoPage" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Name">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Salutation"/>
                <xs:element ref="LastName"/>
                <xs:element ref="FirstName"/>
                <xs:element name="MiddleName" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Salutation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mr" type="xs:boolean"/>
                <xs:element name="Mrs" type="xs:boolean"/>
                <xs:element name="Ms" type="xs:boolean"/>
                <xs:element name="Miss" type="xs:boolean"/>
                <xs:element name="Other" type="xs:boolean" minOccurs="0"/>
                <xs:element name="OtherName" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Address1" type="xs:string"/>
                <xs:element name="Address2" type="xs:string"/>
                <xs:element name="Address3" type="xs:string"/>
                <xs:element name="Postcode" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Telephone" type="xs:string"/>
    <xs:element name="DOB" type="xs:string"/>
    <xs:element name="Email" type="xs:string"/>
    <xs:element name="Attorney"/>
    <xs:element name="DXDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DXNumber" type="xs:string"/>
                <xs:element name="DXExchange" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Relationship">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CivilPartnerSpouse" type="xs:boolean"/>
                <xs:element name="Child" type="xs:boolean"/>
                <xs:element name="Solicitor" type="xs:boolean"/>
                <xs:element name="Other" type="xs:boolean"/>
                <xs:element name="OtherProfessional" type="xs:boolean"/>
                <xs:element name="OtherName" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>If other or other professional, please specify</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Notification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NoticeDate" type="xs:string"/>
                <xs:element name="LastName" type="xs:string"/>
                <xs:element name="FirstName" type="xs:string"/>
                <xs:element ref="Address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="IorWe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="I" type="xs:boolean"/>
                <xs:element name="We" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Date" type="xs:string"/>
    <xs:element name="YesorNo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Yes" type="xs:boolean"/>
                <xs:element name="No" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="LastName" type="xs:string"/>
    <xs:element name="FirstName" type="xs:string"/>
    <xs:element name="Declaration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Signed" type="xs:string"/>
                <xs:element ref="Date"/>
                <xs:element ref="LastName"/>
                <xs:element ref="FirstName"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CompanyName" type="xs:string"/>
    <xs:element name="Occupation" type="xs:string"/>
    <xs:element name="BURN" type="xs:string"/>
    <xs:element name="PhysicalPage" type="xs:int"/>
    <xs:element name="Signature" type="xs:boolean"/>
    <xs:element name="FullName" type="xs:string"/>
</xs:schema>

=== ministryofjustice/opg-scanning/testdata/xml/LP2-valid.xml
<?xml version="1.0" encoding="utf-8"?>
<LP2 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xsi:noNamespaceSchemaLocation="LP2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Page1>
        <Section1>
            <Title>Prof</Title>
            <FirstName>Flavio</FirstName>
            <LastName>Miller</LastName>
            <PropertyFinancialAffairs>0</PropertyFinancialAffairs>
            <HealthWelfare>1</HealthWelfare>
        </Section1>
        <BURN>string</BURN>
        <PhysicalPage>1</PhysicalPage>
    </Page1>
    <Page2>
        <Section2>
            <DonorRegisteration>true</DonorRegisteration>
            <AttorneyRegisteration>false</AttorneyRegisteration>
            <Attorney>
                <Title>Mrs</Title>
                <FirstName>Margret</FirstName>
                <LastName>Jenkins-Barrows</LastName>
                <DOB>24061963</DOB>
            </Attorney>
            <Attorney>
                <Title>Mr</Title>
                <FirstName>Julius Jaden</FirstName>
                <LastName>Heidenreich</LastName>
                <DOB>18021996</DOB>
            </Attorney>
            <Attorney>
                <Title></Title>
                <FirstName></FirstName>
                <LastName></LastName>
                <DOB></DOB>
            </Attorney>
            <Attorney>
                <Title></Title>
                <FirstName></FirstName>
                <LastName></LastName>
                <DOB></DOB>
            </Attorney>
        </Section2>
        <BURN>string</BURN>
        <PhysicalPage>2</PhysicalPage>
    </Page2>
    <Page3>
        <Section3>
            <TheDonor>true</TheDonor>
            <AnAttorney>false</AnAttorney>
            <Other>false</Other>
            <Title></Title>
            <FirstName></FirstName>
            <LastName></LastName>
            <Company></Company>
            <Address>
                <Address1></Address1>
                <Address2></Address2>
                <Address3></Address3>
                <Postcode></Postcode>
            </Address>
            <Post>true</Post>
            <Phone>false</Phone>
            <PhoneNumber></PhoneNumber>
            <Email>false</Email>
            <EmailAddress></EmailAddress>
            <Welsh>false</Welsh>
        </Section3>
        <BURN>string</BURN>
        <PhysicalPage>3</PhysicalPage>
    </Page3>
    <Page4>
        <Section4>
            <Cheque>false</Cheque>
            <Card>true</Card>
            <PhoneNumber>018310 31295</PhoneNumber>
            <ReducedFee>false</ReducedFee>
        </Section4>
        <BURN>string</BURN>
        <PhysicalPage>4</PhysicalPage>
    </Page4>
    <Page5>
        <Section5>
            <Attorney>
                <Signature>true</Signature>
                <Date>18022025</Date>
            </Attorney>
            <Attorney>
                <Signature>true</Signature>
                <Date>18022025</Date>
            </Attorney>
            <Attorney>
                <Signature>false</Signature>
                <Date></Date>
            </Attorney>
            <Attorney>
                <Signature>false</Signature>
                <Date></Date>
            </Attorney>
        </Section5>
        <BURN>string</BURN>
        <PhysicalPage>5</PhysicalPage>
    </Page5>
    <Page6>
        <Section6>
            <Addresses>
                <Title>Mrs</Title>
                <FirstName>Margret</FirstName>
                <LastName>Jenkins-Barrows</LastName>
                <Address>
                    <Address1>77 Jaskolski Field</Address1>
                    <Address2>Konopelski-on-Christiansen</Address2>
                    <Address3>Cronaley</Address3>
                    <Postcode>KB24 4KY</Postcode>
                </Address>
                <EmailAddress></EmailAddress>
            </Addresses>
            <Addresses>
                <Title>Mr</Title>
                <FirstName>Julius Jaden</FirstName>
                <LastName>Heidenreich</LastName>
                <Address>
                    <Address1>304 Dakota Brae</Address1>
                    <Address2>St. Dickihill</Address2>
                    <Address3></Address3>
                    <Postcode>IK5 7QT</Postcode>
                </Address>
                <EmailAddress>jjheidenreich@business.example</EmailAddress>
            </Addresses>
            <Addresses>
                <Title></Title>
                <FirstName></FirstName>
                <LastName></LastName>
                <Address>
                    <Address1></Address1>
                    <Address2></Address2>
                    <Address3></Address3>
                    <Postcode></Postcode>
                </Address>
                <EmailAddress></EmailAddress>
            </Addresses>
            <Addresses>
                <Title></Title>
                <FirstName></FirstName>
                <LastName></LastName>
                <Address>
                    <Address1></Address1>
                    <Address2></Address2>
                    <Address3></Address3>
                    <Postcode></Postcode>
                </Address>
                <EmailAddress></EmailAddress>
            </Addresses>
        </Section6>
        <BURN>string</BURN>
        <PhysicalPage>6</PhysicalPage>
    </Page6>
    <InfoPage>
        <BURN>string</BURN>
        <PhysicalPage>7</PhysicalPage>
    </InfoPage>
</LP2>
