=== ministryofjustice/opg-scanning/xsd/LPA116.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 sp1 (x64) (http://www.altova.com) by Andrew Roberts (BancTec) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="LPA116">
		<xs:annotation>
			<xs:documentation>Continuation sheet PartCLasting power of attorney</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Page1" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PartC">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Attorney">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="Signature"/>
													<xs:element name="FullName" type="xs:string"/>
													<xs:element ref="Date"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Witness">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="Signature"/>
													<xs:element name="FullName" type="xs:string"/>
													<xs:element ref="Address"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element ref="BURN"/>
							<xs:element ref="PhysicalPage"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="InfoPage" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BURN"/>
							<xs:element ref="PhysicalPage"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Salutation"/>
				<xs:element ref="LastName"/>
				<xs:element ref="FirstName"/>
				<xs:element name="MiddleName" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Salutation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Mr" type="xs:boolean"/>
				<xs:element name="Mrs" type="xs:boolean"/>
				<xs:element name="Ms" type="xs:boolean"/>
				<xs:element name="Miss" type="xs:boolean"/>
				<xs:element name="Other" type="xs:boolean"/>
				<xs:element name="OtherName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Address1" type="xs:string"/>
				<xs:element name="Address2" type="xs:string"/>
				<xs:element name="Address3" type="xs:string"/>
				<xs:element name="Address4" type="xs:string"/>
				<xs:element name="Postcode" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Telephone" type="xs:string"/>
	<xs:element name="DOB" type="xs:string"/>
	<xs:element name="Email" type="xs:string"/>
	<xs:element name="Attorney"/>
	<xs:element name="DXDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DXNumber" type="xs:string"/>
				<xs:element name="DXExchange" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CivilPartnerSpouse" type="xs:boolean"/>
				<xs:element name="Child" type="xs:boolean"/>
				<xs:element name="Solicitor" type="xs:boolean"/>
				<xs:element name="Other" type="xs:boolean"/>
				<xs:element name="OtherProfessional" type="xs:boolean"/>
				<xs:element name="OtherName" type="xs:string">
					<xs:annotation>
						<xs:documentation>If other or other professional, please specify</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Notification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NoticeDate" type="xs:string"/>
				<xs:element name="LastName" type="xs:string"/>
				<xs:element name="FirstName" type="xs:string"/>
				<xs:element ref="Address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IorWe">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="I" type="xs:boolean"/>
				<xs:element name="We" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Date" type="xs:string"/>
	<xs:element name="YesorNo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Yes" type="xs:boolean"/>
				<xs:element name="No" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LastName" type="xs:string"/>
	<xs:element name="FirstName" type="xs:string"/>
	<xs:element name="Declaration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Signed" type="xs:string"/>
				<xs:element ref="Date"/>
				<xs:element ref="LastName"/>
				<xs:element ref="FirstName"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompanyName" type="xs:string"/>
	<xs:element name="Occupation" type="xs:string"/>
	<xs:element name="BURN" type="xs:string"/>
	<xs:element name="PhysicalPage" type="xs:int"/>
	<xs:element name="Signature" type="xs:boolean"/>
	<xs:element name="FullName" type="xs:string"/>
</xs:schema>

=== ministryofjustice/opg-scanning/service-app/testdata/xml/LPA116-valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<LPA116 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LPA116.xsd">
  <Page1>
    <PartC>
      <Attorney>
        <Signature>true</Signature>
        <FullName>John Attorney</FullName>
        <Date>01012025</Date>
      </Attorney>
      <Witness>
        <Signature>true</Signature>
        <FullName>Jane Witness</FullName>
        <Address>
          <Address1>456 Other Street</Address1>
          <Address2>Apt 789</Address2>
          <Address3>Townsville</Address3>
          <Address4>County</Address4>
          <Postcode>ZZ99 9ZZ</Postcode>
        </Address>
      </Witness>
    </PartC>
    <BURN/>
    <PhysicalPage>1</PhysicalPage>
  </Page1>
  <InfoPage>
    <BURN/>
    <PhysicalPage>2</PhysicalPage>
  </InfoPage>
</LPA116>
