=== ministryofjustice/opg-scanning/xsd/LPC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 (x64) (http://www.altova.com) by Elaine Matthews (Banctec Limited) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
    <xs:element name="LPC">
        <xs:annotation>
            <xs:documentation>Continuation sheets</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Page1" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ContinuationSheet1">
                                <xs:annotation>
                                    <xs:documentation>AdditionalPeople</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Attorney" minOccurs="2" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Attorney" type="xs:boolean"/>
                                                    <xs:element name="ReplacementAttorney" type="xs:boolean"/>
                                                    <xs:element name="PersonToNotify" type="xs:boolean"/>
                                                    <xs:element name="Title" type="xs:string"/>
                                                    <xs:element ref="FirstName"/>
                                                    <xs:element ref="LastName"/>
                                                    <xs:element ref="DOB"/>
                                                    <xs:element ref="Address"/>
                                                    <xs:element ref="Email"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Donor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="FullName"/>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="Date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page2" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ContinuationSheet2">
                                <xs:annotation>
                                    <xs:documentation>Additional Information</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="AdditionalInformation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Notes" type="xs:boolean"/>
                                                    <xs:element name="Instructions" type="xs:boolean"/>
                                                    <xs:element name="Preferences" type="xs:boolean"/>
                                                    <xs:element name="ReplacementAttorneys" type="xs:boolean"/>
                                                    <xs:element name="Jointly" type="xs:boolean"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Donor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="FullName"/>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="Date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page3" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ContinuationSheet3">
                                <xs:annotation>
                                    <xs:documentation>If the donor cannot sign or mark</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Donor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="FullName"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Signatory">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="FullName"/>
                                                    <xs:element ref="Date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Witnesses" minOccurs="2" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="FullName"/>
                                                    <xs:element ref="Address"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Page4" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ContinuationSheet4">
                                <xs:annotation>
                                    <xs:documentation>Trust corporation appointed as an attorney</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CompanyRegistration" type="xs:string"/>
                                        <xs:element name="AuthorisedPerson" minOccurs="2" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="Signature"/>
                                                    <xs:element ref="FullName"/>
                                                    <xs:element ref="Date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="BURN"/>
                            <xs:element ref="PhysicalPage"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Name">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Salutation"/>
                <xs:element ref="LastName"/>
                <xs:element ref="FirstName"/>
                <xs:element name="MiddleName" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Salutation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mr" type="xs:boolean"/>
                <xs:element name="Mrs" type="xs:boolean"/>
                <xs:element name="Ms" type="xs:boolean"/>
                <xs:element name="Miss" type="xs:boolean"/>
                <xs:element name="Other" type="xs:boolean" minOccurs="0"/>
                <xs:element name="OtherName" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Address1" type="xs:string"/>
                <xs:element name="Address2" type="xs:string"/>
                <xs:element name="Address3" type="xs:string"/>
                <xs:element name="Postcode" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Telephone" type="xs:string"/>
    <xs:element name="DOB" type="xs:string"/>
    <xs:element name="Email" type="xs:string"/>
    <xs:element name="Attorney"/>
    <xs:element name="DXDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DXNumber" type="xs:string"/>
                <xs:element name="DXExchange" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Relationship">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CivilPartnerSpouse" type="xs:boolean"/>
                <xs:element name="Child" type="xs:boolean"/>
                <xs:element name="Solicitor" type="xs:boolean"/>
                <xs:element name="Other" type="xs:boolean"/>
                <xs:element name="OtherProfessional" type="xs:boolean"/>
                <xs:element name="OtherName" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>If other or other professional, please specify</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Notification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NoticeDate" type="xs:string"/>
                <xs:element name="LastName" type="xs:string"/>
                <xs:element name="FirstName" type="xs:string"/>
                <xs:element ref="Address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="IorWe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="I" type="xs:boolean"/>
                <xs:element name="We" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Date" type="xs:string"/>
    <xs:element name="YesorNo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Yes" type="xs:boolean"/>
                <xs:element name="No" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="LastName" type="xs:string"/>
    <xs:element name="FirstName" type="xs:string"/>
    <xs:element name="Declaration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Signed" type="xs:string"/>
                <xs:element ref="Date"/>
                <xs:element ref="LastName"/>
                <xs:element ref="FirstName"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CompanyName" type="xs:string"/>
    <xs:element name="Occupation" type="xs:string"/>
    <xs:element name="BURN" type="xs:string"/>
    <xs:element name="PhysicalPage" type="xs:int"/>
    <xs:element name="Signature" type="xs:boolean"/>
    <xs:element name="FullName" type="xs:string"/>
</xs:schema>

=== ministryofjustice/opg-scanning/testdata/xml/LPC-valid.xml
<LPC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="LPC.xsd">
    <Page1>
        <ContinuationSheet1>
            <Attorney>
                <Attorney>true</Attorney>
                <ReplacementAttorney>false</ReplacementAttorney>
                <PersonToNotify>false</PersonToNotify>
                <Title>Mr</Title>
                <FirstName>Jack</FirstName>
                <LastName>Jones</LastName>
                <DOB>1970-01-01</DOB>
                <Address>
                    <Address1>1 Example Road</Address1>
                    <Address2>Example Town</Address2>
                    <Address3>Example County</Address3>
                    <Postcode>EX4 MPL</Postcode>
                </Address>
                <Email>john.doe@example.com</Email>
            </Attorney>

            <Attorney>
                <Attorney>false</Attorney>
                <ReplacementAttorney>true</ReplacementAttorney>
                <PersonToNotify>false</PersonToNotify>
                <Title>Mrs</Title>
                <FirstName>Mary</FirstName>
                <LastName>Smith</LastName>
                <DOB>1975-05-05</DOB>
                <Address>
                    <Address1>2 Example Avenue</Address1>
                    <Address2>Example Town</Address2>
                    <Address3>Example County</Address3>
                    <Postcode>EX4 MPL</Postcode>
                </Address>
                <Email>mary.smith@example.com</Email>
            </Attorney>

            <Donor>
                <FullName>Jane Donor</FullName>
                <Signature>true</Signature>
                <Date>2025-01-29</Date>
            </Donor>
        </ContinuationSheet1>
        <BURN>Valid BURN text</BURN>
        <PhysicalPage>1</PhysicalPage>
    </Page1>

    <Page2>
        <ContinuationSheet2>
            <AdditionalInformation>
                <Notes>true</Notes>
                <Instructions>true</Instructions>
                <Preferences>true</Preferences>
                <ReplacementAttorneys>false</ReplacementAttorneys>
                <Jointly>false</Jointly>
            </AdditionalInformation>
            <Donor>
                <FullName>John Donor</FullName>
                <Signature>true</Signature>
                <Date>2025-01-29</Date>
            </Donor>
        </ContinuationSheet2>
        <BURN>Valid BURN text</BURN>
        <PhysicalPage>2</PhysicalPage>
    </Page2>

    <Page3>
        <ContinuationSheet3>
            <Donor>
                <FullName>John Donor</FullName>
            </Donor>

            <Signatory>
                <Signature>true</Signature>
                <FullName>James Signatory</FullName>
                <Date>2025-01-29</Date>
            </Signatory>

            <Witnesses>
                <Signature>true</Signature>
                <FullName>Witness 1</FullName>
                <Address>
                    <Address1>3 Example Road</Address1>
                    <Address2>Example Town</Address2>
                    <Address3></Address3>
                    <Postcode>EX4 MPL</Postcode>
                </Address>
            </Witnesses>

            <Witnesses>
                <Signature>true</Signature>
                <FullName>Witness 2</FullName>
                <Address>
                    <Address1>3 Example Road</Address1>
                    <Address2>Example Town</Address2>
                    <Address3></Address3>
                    <Postcode>EX4 MPL</Postcode>
                </Address>
            </Witnesses>
        </ContinuationSheet3>
        <BURN>Valid BURN text</BURN>
        <PhysicalPage>3</PhysicalPage>
    </Page3>

    <Page4>
        <ContinuationSheet4>
            <CompanyRegistration>Company12345</CompanyRegistration>

            <AuthorisedPerson>
                <Signature>true</Signature>
                <FullName>Authorized Person 1</FullName>
                <Date>2025-01-29</Date>
            </AuthorisedPerson>

            <AuthorisedPerson>
                <Signature>true</Signature>
                <FullName>Authorized Person 2</FullName>
                <Date>2025-01-29</Date>
            </AuthorisedPerson>
        </ContinuationSheet4>
        <BURN>Valid BURN text</BURN>
        <PhysicalPage>4</PhysicalPage>
    </Page4>
</LPC>
